### PR TITLE
new "except" filter for negating IPs

### PR DESCRIPTION
**Pull request by anheric**
I wanted to block a country but allow an IP of that country. Didn't seem possible without this but covered my case now!
It is a naive approach but might spark better ideas. Only tested one case so far

### CODE REVIEW

**Comment by pyed** [comment]
Thank you for taking the time to report and implement a solution for your issue.

But I don't think that we should have it as a part of ipfilter, it's rarely needed and it introduce a new config keyword, lots of code, and one more check for every request, Maybe there's a better way of solving it.

**Comment by anheric** [comment]
Absolutely, I should have mentioned this on an enhancement issue, not a PR.
I hope to make some time in the future for a better design

**Comment by krader1961** [comment]
Should this be closed since it isn't going to be merged?

Also, given the existing behavior it is sufficient, if perhaps slightly awkward, to order the rules so the country block occurs before the rule to allow the IP. That is, this change isn't needed.  For example, I can disallow any access from an IP address whose country cannot be resolved (such as my loopback address):

```
    ipfilter / {
        database /Users/krader/etc/GeoLite2-Country.mmdb
        rule block
        country ""
    }
```

If I add the following rule after the preceding rule it allows `curl -D h http://localhost:8082/ > x` despite the IPv6 loopback address not having an associated country:

```
    ipfilter / {
        rule allow
        ip ::1
    }
```

This scenario should probably be better documented.

**Comment by anheric** [comment]
Thank you @krader1961 for the example and you're right, this PR should be closed

**Pull request closed without merging**
